INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (1, '20.90.1234', 'Mansur Tri', 'L', 'Teknik Komputer', 'Yogyakarta');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (2, '20.90.1235', 'Agung Surya', 'L', 'Informatika', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (3, '20.90.1236', 'Krisna Imran', 'L', 'Sistem Informasi', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (4, '20.90.1237', 'Kusuma Ruslan', 'L', 'Teknologi Informasi', 'Gunung Kidul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (5, '20.90.1238', 'Bagus Sri', 'L', 'Teknik Elektro', 'Kulonprogo');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (6, '20.90.1239', 'Irfan Harun', 'L', 'Informatika', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (7, '20.90.1230', 'Dian Akhmad', 'L', 'Informatika', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (8, '20.90.1231', 'Lutfi Ali', 'L', 'Sistem Informasi', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (9, '20.90.1232', 'Zulfikar Amir', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (10, '20.90.1232', 'Yuda Ismail', 'L', 'Teknologi Informasi', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (11, '20.90.1241', 'Saiful Lutfi', 'L', 'Teknik Komputer', 'Gunung Kidul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (12, '20.90.1242', 'Mahmud Amir', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (13, '20.90.1243', 'Buana Wira', 'L', 'Teknik Elektro', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (14, '20.90.1244', 'Zakaria Aditya', 'L', 'Teknik Elektro', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (15, '20.90.1245', 'Bima Hasan', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (16, '20.90.1246', 'Dwi Anwar', 'L', 'Teknik Komputer', 'Gunung Kidul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (17, '20.90.1247', 'Eka Imran', 'L', 'Teknik Komputer', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (18, '20.90.1248', 'Bachtiar Abdul', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (19, '20.90.1249', 'Akbar Lutfi', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (20, '20.90.1250', 'Adi Eka', 'L', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (21, '20.90.1252', 'Nur Arif', 'L', 'Sistem Informasi', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (22, '20.90.1253', 'Tirto Guntur', 'L', 'Sistem Informasi', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (23, '20.90.1251', 'Akhmad Ahmad', 'L', 'Teknik Komputer', 'Gunung Kidul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (24, '20.90.1255', 'Muhamad Anwar', 'L', 'Sistem Informasi', 'Yogyakarta');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (25, '20.90.1254', 'Amir Mansur', 'L', 'Teknik Komputer', 'Gunung Kidul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (26, '20.90.1257', 'Wati Sri Batari', 'P', 'Informatika', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (27, '20.90.1256', 'Annisa Ratna Dwi', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (28, '20.90.1258', 'Aisyah Annisa Vina', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (29, '20.90.1259', 'Kusuma Nurul Kasih', 'P', 'Informatika', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (30, '20.90.1261', 'Dwi Yuliana Nurul', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (31, '20.90.1260', 'Wangi Tri Kasih', 'P', 'Teknik Komputer', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (32, '20.90.1263', 'Mawar Yuliana Nirmala', 'P', 'Teknologi Informasi', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (33, '20.90.1265', 'Wangi Putri Siti', 'P', 'Teknologi Informasi', 'Kulonprogo');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (34, '20.90.1264', 'Annisa Aisyah Cahaya', 'P', 'Teknik Komputer', 'Kulonprogo');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (35, '20.90.1266', 'Aisyah Ratna Fatimah', 'P', 'Teknik Komputer', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (36, '20.90.1267', 'Kusuma Latifah Yuliana', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (37, '20.90.1268', 'Cahaya Intan Melati', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (38, '20.90.1269', 'Asih Alya Tri', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (39, '20.90.1270', 'Nirmala Mega Ratna', 'P', 'Teknik Komputer', 'Yogyakarta');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (40, '20.90.1271', 'Ratna Siti Kusuma', 'P', 'Teknik Komputer', 'Kulonprogo');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (41, '20.90.1272', 'Batari Iman Alya', 'P', 'Teknik Komputer', 'Kulonprogo');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (42, '20.90.1273', 'Vina Mawar Aminah', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (43, '20.90.1274', 'Tirta Wati Sitti', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (44, '20.90.1275', 'Dewi Tirta Fatimah', 'P', 'Teknologi Informasi', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (45, '20.90.1276', 'Kusuma Bulan Kasih', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (46, '20.90.1277', 'Indah Nirmala Intan', 'P', 'Sistem Informasi', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (47, '20.90.1278', 'Fatimah Alya Sitti', 'P', 'Teknik Komputer', 'Yogyakarta');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (48, '20.90.1279', 'Batari Fatimah Aminah', 'P', 'Sistem Informasi', 'Bantul');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (49, '20.90.1280', 'Fatimah Putri Tirta', 'P', 'Teknik Komputer', 'Sleman');
INSERT INTO `tbl_students_0584` (`id`, `nim`, `nama`, `jk`, `jurusan`, `alamat`) VALUES (50, '20.90.1288', 'Intan Mawar Anisa', 'P', 'Teknik Komputer', 'Yogyakarta');